# This file is part of Flipper Open Reverse Image Search.
#
# Flipper Open Reverse Image Search is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Flipper Open Reverse Image Search is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Flipper Open Reverse Image Search.  If not, see <http://www.gnu.org/licenses/>.

server:
    port: 8080

liquibase:
    context: dev

spring:
    profiles:
        active: dev
    data:
        cassandra:
            contactPoints: localhost
            protocolVersion: V3
            compression: LZ4
            keyspaceName: flipper

        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                  logs: target/elasticsearch/log
                  data: target/elasticsearch/data

    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: flipper


