# This file is part of Flipper Open Reverse Image Search.
#
# Flipper Open Reverse Image Search is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Flipper Open Reverse Image Search is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Flipper Open Reverse Image Search.  If not, see <http://www.gnu.org/licenses/>.

# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
### CHANGE THIS VALUE IN PRODUCTION MODE!
jhipster.security.rememberme.key: 1ba17bd827c4c22037e2e62562ac5c8f06ddde34

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

### CHANGE THIS VALUE IN PRODUCTION MODE!
mail:
    host: smtp.mailgun.org
    port: 465
    username: postmaster@yourdomain-from-mailgun-servie.mailgun.org
    password: yourpassword-from-your-mailgun-service
    protocol: smtps
    tls: true
    auth: true
    from: no-reply@localhost

### CHANGE THIS VALUE IN PRODUCTION MODE!
authentication:
    xauth:
        secret: myXAuthSecret
        # Token is valid 30 minutes
        tokenValidityInSeconds: 1800

spring:
    mvc:
        favicon:
            enabled: false

swagger:
    title: flipper API
    description: flipper applications and beyond!
    version: 0.0.1
    termsOfServiceUrl: https://github.com/dalbelap/flipper-reverse-image-search
    contact:
    license: GNU GPL v3
    licenseUrl: http://www.gnu.org/licenses/gpl-3.0.en.html
